=== Nereee/E4_ML_T4/datuak/intra.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="erakundea">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="departamentuak">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="departamentua" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="izena" type="xsd:string" />
                                        <xsd:element name="helbidea">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="herrialdea" type="xsd:string" />
                                                    <xsd:element name="probintzia" type="xsd:string" />
                                                    <xsd:element name="herria">
                                                        <xsd:complexType>
                                                            <xsd:simpleContent>
                                                                <xsd:extension base="xsd:string">
                                                                    <xsd:attribute name="posta_k"
                                                                        type="xsd:string" />
                                                                </xsd:extension>
                                                            </xsd:simpleContent>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="kalea" type="xsd:string" />
                                                    <xsd:element name="zenbakia" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="telefonoa" type="xsd:string" />
                                        <xsd:element name="e_posta" type="xsd:string" />
                                        <xsd:element name="menpeko-departamentua" type="xsd:string" />
                                        <xsd:element name="departamentu-burua" type="xsd:string" />
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:string" />
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="langileak">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="langilea" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="izena" type="xsd:string" />
                                        <xsd:element name="abizena1" type="xsd:string" />
                                        <xsd:element name="abizena2" type="xsd:string" />
                                        <xsd:element name="jaoiotze_data" type="xsd:string" />
                                        <xsd:element name="bizilekua">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="herrialdea" type="xsd:string" />
                                                    <xsd:element name="probintzia" type="xsd:string" />
                                                    <xsd:element name="herria">
                                                        <xsd:complexType>
                                                            <xsd:simpleContent>
                                                                <xsd:extension base="xsd:string">
                                                                    <xsd:attribute name="posta_k"
                                                                        type="xsd:string" />
                                                                </xsd:extension>
                                                            </xsd:simpleContent>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="kalea" type="xsd:string" />
                                                    <xsd:element name="zenbakia" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="telefonoak">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="mugikorra" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="e-postak">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="pertsonala" type="xsd:string" />
                                                    <xsd:element name="lanekoa" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="argazkia" type="xsd:string" />
                                        <xsd:element name="soldata" type="xsd:decimal" />
                                        <xsd:element name="kontratazio-data" type="xsd:string" />
                                        <xsd:element name="rola" type="xsd:string"
                                            maxOccurs="unbounded" />
                                        <xsd:element name="departamentua" type="xsd:string" />
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:string" />
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="rolak">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="rol" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="izena" type="xsd:string" />
                                        <xsd:element name="deskripzioa" type="xsd:string" />
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:string" />
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Nereee/E4_ML_T4/datuak/intra.xml
<?xml version="1.0" encoding="UTF-8"?>
<erakundea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="intra.xsd">
    <departamentuak>
        <!-- Departamentua 1-->
        <departamentua id="1">
            <izena>Giza_baliabideak</izena>
            <argazkia>./image/departamentua.png</argazkia>
            <helbidea>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48011">Bilbo</herria>
                <kalea>Juan de la Cosa</kalea>
                <zenbakia>15</zenbakia>
            </helbidea>
            <telefonoa>456456456</telefonoa>
            <e_posta>intragizabal@gmail.com</e_posta>
            <menpeko-departamentua></menpeko-departamentua>
            <departamentu-burua>4</departamentu-burua>
        </departamentua>
        <!-- Departamentua 2-->
        <departamentua id="2">
            <izena>Marketin</izena>
            <argazkia>./image/departamentua.png</argazkia>
            <helbidea>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48011">Bilbo</herria>
                <kalea>Calle Santutxu</kalea>
                <zenbakia>20</zenbakia>
            </helbidea>
            <telefonoa>123123123</telefonoa>
            <e_posta>intramark@gmail.com</e_posta>
            <menpeko-departamentua></menpeko-departamentua>
            <departamentu-burua>5</departamentu-burua>
        </departamentua>
        <!-- Departamentua 3-->
        <departamentua id="3">
            <izena>Zuzendaritza Orokorra</izena>
            <argazkia>./image/departamentua.png</argazkia>
            <helbidea>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48009">Bilbo</herria>
                <kalea>Alameda de Mazarredo</kalea>
                <zenbakia>25</zenbakia>
            </helbidea>
            <telefonoa>890890890</telefonoa>
            <e_posta>intrzuzendaritza@gmail.com</e_posta>
            <menpeko-departamentua></menpeko-departamentua>
            <departamentu-burua>3</departamentu-burua>
        </departamentua>
        <!-- Departamentua 4-->
        <departamentua id="4">
            <izena>Lege-Saila</izena>
            <argazkia>./image/departamentua.png</argazkia>
            <helbidea>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48480">Arrigorriaga</herria>
                <kalea>Calle Dr.Fleming</kalea>
                <zenbakia>4</zenbakia>
            </helbidea>
            <telefonoa>678678678</telefonoa>
            <e_posta>intrlegesail@gmail.com</e_posta>
            <menpeko-departamentua></menpeko-departamentua>
            <departamentu-burua>8</departamentu-burua>
        </departamentua>
        <!-- Departamentua 5-->
        <departamentua id="5">
            <izena>Salmentak</izena>
            <argazkia>./image/departamentua.png</argazkia>
            <helbidea>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48970">Basauri</herria>
                <kalea>Kareaga Goikoa</kalea>
                <zenbakia>16</zenbakia>
            </helbidea>
            <telefonoa>934934934</telefonoa>
            <e_posta>intrsalmentak@gmail.com</e_posta>
            <menpeko-departamentua></menpeko-departamentua>
            <departamentu-burua>14</departamentu-burua>
        </departamentua>
        <!-- Departamentua 6-->
        <departamentua id="6">
            <izena>Ekoizpena</izena>
            <argazkia>./image/departamentua.png</argazkia>
            <helbidea>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48480">Arrigorriaga</herria>
                <kalea>Santa Isabel</kalea>
                <zenbakia>7</zenbakia>
            </helbidea>
            <telefonoa>934934934</telefonoa>
            <e_posta>intrsalmentak@gmail.com</e_posta>
            <menpeko-departamentua></menpeko-departamentua>
            <departamentu-burua>9</departamentu-burua>
        </departamentua>

    </departamentuak>
    <langileak>
        <!-- Langilea 1 -->
        <langilea id="1">
            <izena>Aitzol</izena>
            <abizena1>Sagardui</abizena1>
            <abizena2>Larrinaga</abizena2>
            <jaoiotze_data>2005-03-11</jaoiotze_data>
            <bizilekua>
                <herrialdea>España</herrialdea>
                <probintzia>Bizkaia</probintzia>
                <herria posta_k="48480">Arrigorriaga</herria>
                <kalea>Ramon y cajal</kalea>
                <zenbakia>9</zenbakia>
            </bizilekua>
            <telefonoak>
                <mugikorra>987908798</mugikorra>
            </telefonoak>
            <e-postak>
                <pertsonala>aitzolsagardui@gmail.com</pertsonala>
                <lanekoa>intraaitzol@gmail.com</lanekoa>
            </e-postak>
            <argazkia>./image/empleado.png</argazkia>
            <soldata>2000</soldata>
            <kontratazio-data>2000-09-02</kontratazio-data>
            <rola>rh</rola>
            <departamentua>1</departamentua>
        </langilea>
        <!-- Langilea 2 -->
        <langilea id="2">
            <izena>Mireia</izena>
            <abizena1>López</abizena1>
            <abizena2>García</abizena2>
            <jaoiotze_data>1990-07-15</jaoiotze_data>
            <bizilekua>
                <herrialdea>España</herrialdea>
                <probintzia>Barcelona</probintzia>
                <herria posta_k="08002">Barcelona</herria>
                <kalea>Avenida Diagonal</kalea>
                <zenbakia>123</zenbakia>
            </bizilekua>
            <telefonoak>
                <mugikorra>654321987</mugikorra>
            </telefonoak>
            <e-postak>
                <pertsonala>mireialopez@gmail.com</pertsonala>
                <lanekoa>mlopez@empresa.com</lanekoa>
            </e-postak>
            <argazkia>./image/empleada.png</argazkia>
            <soldata>2500</soldata>
            <kontratazio-data>2015-04-20</kontratazio-data>
            <rola>rh</rola>
            <departamentua>1</departamentua>
        </langilea>

        <!-- Langilea 3 -->
        <langilea id="3">
            <izena>Jon</izena>
            <abizena1>González</abizena1>
            <abizena2>Ruiz</abizena2>
            <jaoiotze_data>1985-12-03</jaoiotze_data>
            <bizilekua>
                <herrialdea>España</herrialdea>
                <probintzia>Madrid</probintzia>
                <herria posta_k="28001">Madrid</herria>
                <kalea>Calle Gran Vía</kalea>
                <zenbakia>45</zenbakia>
            </bizilekua>
            <telefonoak>
                <mugikorra>678945612</mugikorra>
            </telefonoak>
            <e-postak>
                <pertsonala>jon.gr@gmail.com</pertsonala>
                <lanekoa>jgonzalez@company.com</lanekoa>
            </e-postak>
            <argazkia>./image/empleado.png</argazkia>
            <soldata>2800</soldata>
            <kontratazio-data>2010-08-10</kontratazio-data>
            <rola>pr</rola>
            <departamentua>6</departamentua>
        </langilea>

        <!-- Langilea 4 -->
        <langilea id="4">
            <izena>María</izena>
            <abizena1>Rodríguez</abizena1>
            <abizena2>Fernández</abizena2>
            <jaoiotze_data>1978-05-20</jaoiotze_data>
            <bizilekua>
                <herrialdea>España</herrialdea>
                <probintzia>Valencia</probintzia>
                <herria posta_k="46001">Valencia</herria>
                <kalea>Avenida del Puerto</kalea>
                <zenbakia>78</zenbakia>
            </bizilekua>
            <telefonoak>
                <mugikorra>623548976</mugikorra>
            </telefonoak>
            <e-postak>
                <pertsonala>mariarod@gmail.com</pertsonala>
                <lanekoa>mrodriguez@compañia.com</lanekoa>
            </e-postak>
            <argazkia>./image/empleada.png</argazkia>
            <soldata>3200</soldata>
            <kontratazio-data>2004-09-15</kontratazio-data>
            <rola>db</rola>
            <departamentua>6</departamentua>
        </langilea>

        <!-- Langilea 5 -->
        <langilea id="5">
            <izena>Javier</izena>
            <abizena1>Martínez</abizena1>
            <abizena2>Rodríguez</abizena2>
            <jaoiotze_data>1993-02-28</jaoiotze_data>
            <bizilekua>
                <herrialdea>España</herrialdea>
                <probintzia>Alicante</probintzia>
                <herria posta_k="03001">Alicante</herria>
                <kalea>Paseo de la Explanada</kalea>
                <zenbakia>15</zenbakia>
            </bizilekua>
            <telefonoak>
                <mugikorra>632587914</mugikorra>
            </telefonoak>
            <e-postak>
                <pertsonala>javier.martinez@gmail.com</pertsonala>
                <lanekoa>jmartinez@empresa.com</lanekoa>
            </e-postak>
            <argazkia>./image/empleado.png</argazkia>
            <soldata>2700</soldata>
            <kontratazio-data>2018-06-22</kontratazio-data>
            <rola>db</rola>
            <departamentua>5</departamentua>
        </langilea>

        <!-- Langilea 6 -->
        <langilea id="6">
            <izena>Laura</izena>
            <abizena1>Fernández</abizena1>
            <abizena2>Gutierrez</abizena2>
            <jaoiotze_data>1989-09-10</jaoiotze_data>
            <bizilekua>
                <herrialdea>España</herrialdea>
                <probintzia>Sevilla</probintzia>
                <herria posta_k="41001">Sevilla</herria>
                <kalea>Calle Sierpes</kalea>
                <zenbakia>20</zenbakia>
